### ISSUE TITLE
 `StorageProvider` methods [tracking]

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#149]
We will be needing extra methods on `StorageProvider` as we move forward, let's collect them here to get an overview of how things might look. Also as we use it more, we may want to make changes.

Also general renaming, possibly following these conventions more closely: https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv

#### `LogStore`
- [x] rename: `get` to `get_log` or something else better.
- [x] remove `StorageLog` associated type in favour of passing in params
- [x] remove `next_log_id()`

#### `OperationStore`
- [ ] add: `get_operations_by_document_view_id(id: DocumentViewId) -> Result<Vec<Operation>>` https://github.com/p2panda/aquadoggo/issues/148

#### `DocumentStore`
- [x] rename: `get_document_by_id` to `get_latest_view_for_document`
- [x] add: `get_document_by_id` which returns the actual `Document` rather than the view. 
- [ ] add: `get_document_id_by_view_id(document_view_id: DocumentViewId) -> Result<DocumentId>`
- [x] add: `get_document_by_view_id(view_id: DocumentViewId) -> Result<Document>` (returns document with the given view inside, not the latest view)
- [x] change: `get_documents_by_schema(schema: SchemaId) -> Result<Vec<Document>>`
- [x] ~~change: `DocumentMeta.operations: Option<Vec<VerifiedOperation>>`~~
- [x] add: ~`get_parents_with_pinned_relation(document_view_id: &DocumentViewId) -> Result<Vec<DocumentViewId>>` https://github.com/p2panda/aquadoggo/pull/144~
- [x] add: ~`get_parents_with_unpinned_relation(document_view_id: &Documentd) -> Result<Vec<DocumentViewId>>` https://github.com/p2panda/aquadoggo/pull/144~

#### `SchemaStore`
- [ ] add: `get_log_seq_for_schema(schema_id: SchemaId) -> Vec<(Author, Vec<(LogId, SeqNum)>>`

#### `StorageProvider`
- [x] move: any non-top level methods (think there is only one left) to their respective sub-store.
- [x] refactor this out completely in favour of using individual store traits
- [x] remove `get_document_by_entry()` 

#### General
- [ ] look again at the errors we have, room for improvement, simplification, a lot may be redundant now that validation logic is elsewhere
- [x] rename all basic getters simply `get_x()` (now they are `get_x_by_id()`)

#### QUESTIONS:
- do we want an error or `Ok(false)` to be returned from insert methods?
- in general DocumentStore needs a little reflection now we used it a bit, in particular "insert"ing documents is confusing, what do we expect this to do? Create or update a documents latest view id? As well as the view? Delete a document??? Splitting it out into multiple methods might help, Also not having to pass in a `Document` struct would be handy.

**Comment by adzialocha** [comment]
Is this ready? ✨

**Comment by sandreae** [comment]
Unfortunately, no... Couldn't get round to making these changes yet.
